export const servicesSeed = [
  {
    slug: 'labour-law-compliance', title: 'Labour Law Compliance', img: '/assets/service-labour.png',
    desc: 'End-to-end compliance with all applicable central and state labour legislation, shielding your business from penal consequences.',
    headline: 'Streamlining Compliance has never been easier.',
    subhead: 'Labour Law Compliance Services',
    intro: 'End-to-end compliance management for all applicable central and state labour legislation across India.',
    body: 'Navigating the complex web of Indian labour laws requires precision and proactive management. Our Labour Law Compliance service provides end-to-end protection, ensuring your organization remains fully compliant while optimizing operational efficiency.\n\nWith the impending enforcement of the New Labour Codes — consolidating 29 Central Acts into 4 Codes — the regulatory landscape is shifting fundamentally. We audit your current practices, identify structural gaps, and implement frameworks that withstand the highest level of scrutiny from statutory bodies, including the DPIIT, State Labour Departments, and ESI/PF Enforcement Officers.',
    deliverables: [
      { title: 'Comprehensive Compliance Audits', desc: 'Deep-dive reviews across all applicable central and state labour legislation.' },
      { title: 'Statutory Register Maintenance', desc: 'Accurate, inspection-ready registers maintained as per every applicable Act.' },
      { title: 'Risk Assessment & Mitigation', desc: 'Proactive identification and elimination of compliance gaps before they escalate.' },
      { title: 'Liaison with Government Authorities', desc: 'Expert representation in dealings with DPIIT, Labour Departments, and enforcement officers.' },
      { title: 'Regular Regulatory Updates', desc: 'Timely alerts and briefings on new notifications, amendments, and enforcement trends.' },
      { title: 'Documentation Standardization', desc: 'Unified, legally-sound documentation across all establishments and locations.' },
    ],
    order: 0,
  },
  {
    slug: 'payroll-structuring', title: 'Payroll & Salary Structuring', img: '/assets/service-payroll.png',
    desc: 'Precise payroll processing and salary structure auditing optimized for the New Labour Code definitions of wages.',
    headline: 'Precise Payroll Processing, Optimized for New Labour Codes.',
    subhead: 'Payroll & Salary Structuring Services',
    intro: 'Accurate payroll management and salary structure auditing aligned with the New Labour Code definitions of wages.',
    body: 'The New Labour Codes have fundamentally redefined the concept of "wages," directly impacting PF contributions, gratuity calculations, leave encashment, and employee benefits. Non-compliance in payroll structuring can result in significant financial penalties and employee disputes.\n\nOur experts design salary structures that are fully compliant with the Code on Wages, tax-efficient, and aligned with the new 50% basic wage rule — protecting both the employer and employee while minimizing statutory costs.',
    deliverables: [
      { title: 'Salary Structure Redesign', desc: 'Restructure compensation to meet the 50% basic wage rule while optimizing take-home pay.' },
      { title: 'PF & ESIC Computation', desc: 'Accurate monthly contribution calculations compliant with the new wage definition.' },
      { title: 'Full & Final Settlement', desc: 'Legally accurate F&F processing including gratuity, leave encashment, and statutory dues.' },
      { title: 'Payroll Software Integration', desc: 'Seamless setup and integration with HRMS and payroll platforms for error-free processing.' },
      { title: 'Tax Optimization', desc: 'Salary structuring aligned with income tax provisions to maximize in-hand salary legally.' },
      { title: 'Monthly Payroll Processing', desc: 'End-to-end payroll run including disbursement, payslips, and statutory compliance.' },
    ],
    order: 1,
  },
  {
    slug: 'statutory-filings', title: 'Statutory Compliance & Filings', img: '/assets/service-statutory.png',
    desc: 'Flawless management of PF, ESIC, PT, LWF, TDS, alongside regular returns and meticulous statutory filings.',
    headline: 'Flawless Statutory Filings, On Time, Every Time.',
    subhead: 'Statutory Compliance & Filings Services',
    intro: 'Complete management of PF, ESIC, PT, LWF, TDS filings and timely regulatory returns.',
    body: 'Statutory compliance involves a complex, interlocking calendar of filings, payments, and returns across multiple government portals and authorities. A single missed deadline can attract hefty penalties, interest, and even prosecution of directors and HR managers.\n\nOur dedicated statutory team manages the full compliance calendar for your organization — from monthly PF/ESIC contributions to annual returns — ensuring zero delays, zero errors, and complete peace of mind for your leadership team.',
    deliverables: [
      { title: 'PF Monthly Returns', desc: 'Timely ECR uploads and monthly PF contribution processing across all employee categories.' },
      { title: 'ESIC Monthly Contribution', desc: 'Accurate half-yearly returns and monthly contribution payments with zero lapses.' },
      { title: 'Professional Tax Payments', desc: 'State-specific PT calculations, deductions, and timely remittances to authorities.' },
      { title: 'LWF Contributions', desc: 'State-wise Labour Welfare Fund deductions and remittances on schedule.' },
      { title: 'TDS Filings', desc: 'Quarterly TDS returns (Form 24Q) and Form 16 generation for all employees.' },
      { title: 'Annual Statutory Returns', desc: 'All annual returns under applicable Acts — Factories, CLRA, PF, ESIC — filed on time.' },
    ],
    order: 2,
  },
  {
    slug: 'contract-staffing', title: 'People Outsourcing & Staffing', img: '/assets/service-staffing.png',
    desc: 'Flexible, compliant workforce solutions via outsourcing, managing everything from onboarding to full & final exit.',
    headline: 'Flexible, Compliant Workforce Solutions at Scale.',
    subhead: 'People Outsourcing & Staffing Services',
    intro: 'End-to-end management of outsourced workforce — from onboarding to exit, fully compliant.',
    body: 'Contract and temporary staffing comes with a specific set of compliance requirements under the CLRA Act and New Labour Codes. Improper management of contract workers exposes both the principal employer and contractor to significant legal liability, including criminal prosecution.\n\nWe manage the entire lifecycle of your contractual workforce — recruitment, onboarding, payroll, all compliance filings, and exit formalities — giving you the flexibility to scale your workforce without taking on legal risk.',
    deliverables: [
      { title: 'Contract Labour License (CLRA)', desc: 'Procurement and renewal of contractor and principal employer licenses under the CLRA Act.' },
      { title: 'Worker Onboarding & Registration', desc: 'Smooth onboarding with all statutory registrations — PF, ESIC, and labour department records.' },
      { title: 'Payroll for Contract Staff', desc: 'Accurate, compliant payroll processing for all contractual and temporary workers.' },
      { title: 'Monthly Compliance Filings', desc: 'All contractor-specific returns filed on time — registers, muster rolls, and wage statements.' },
      { title: 'Exit & F&F Management', desc: 'Legally compliant full and final settlements for all exiting contract employees.' },
      { title: 'Principal Employer Compliance', desc: 'Ensuring the principal employer meets all obligations under CLRA and New Labour Codes.' },
    ],
    order: 3,
  },
  {
    slug: 'audits-governance', title: 'Audits & Governance', img: '/assets/service-audits.png',
    desc: 'Rigorous labour audits, factory audits, and establishment compliance reviews to identify and seal regulatory gaps.',
    headline: 'Rigorous Audits to Seal Every Compliance Gap.',
    subhead: 'Audits & Governance Services',
    intro: 'Labour audits, factory audits, and establishment reviews to identify and eliminate compliance risks.',
    body: 'A compliance audit is not just a paperwork exercise — it is a strategic risk management tool. Our auditors go beyond surface-level checks to identify deep-rooted vulnerabilities in your payroll structure, statutory registers, employment documentation, and contractor management systems.\n\nWe conduct comprehensive audits across all applicable legislation — Factories Act, Contract Labour Act, EPF Act, ESI Act, and the New Labour Codes — and provide actionable remediation plans, ensuring your establishment is inspection-ready at all times.',
    deliverables: [
      { title: 'Labour Law Compliance Audit', desc: 'End-to-end audit of all applicable labour laws across your establishments and locations.' },
      { title: 'Factory Act Audit', desc: 'Thorough inspection of Factory Act compliance — licensing, safety, welfare, and registers.' },
      { title: 'Payroll Audit', desc: 'Independent verification of payroll calculations, deductions, and statutory contributions.' },
      { title: 'Contract Labour Audit', desc: 'Review of contractor compliance, registers, and principal employer obligations.' },
      { title: 'Remediation Planning', desc: 'Detailed, prioritized action plans to close every gap identified during the audit.' },
      { title: 'Post-Audit Monitoring', desc: 'Ongoing compliance tracking to ensure remediation actions are implemented effectively.' },
    ],
    order: 4,
  },
  {
    slug: 'registrations-licensing', title: 'Registrations & Licensing', img: '/assets/service-licensing.png',
    desc: 'Procurement of Shop & Establishment, Factory License, Contract Labour License with timely renewals.',
    headline: 'All Your Statutory Registrations, Handled End-to-End.',
    subhead: 'Registrations & Licensing Services',
    intro: 'Procurement and timely renewal of Shop & Establishment, Factory License, and Contract Labour License.',
    body: 'Operating without the required licenses and registrations is a significant legal risk that can result in closure notices, prosecution, and inability to bid for government contracts. From new business setup to ongoing renewals, we manage all statutory registrations across India.\n\nOur experts handle the entire process — from documentation preparation and application filing to follow-up with state authorities — ensuring timely approval, zero lapses, and full regulatory standing for your business.',
    deliverables: [
      { title: 'Shop & Establishment Registration', desc: 'State-wise S&E registration and renewal for all commercial establishments.' },
      { title: 'Factory License & Renewal', desc: 'End-to-end factory license procurement and annual renewal under the Factories Act.' },
      { title: 'Contract Labour License (CLRA)', desc: 'Contractor and principal employer license under the Contract Labour (Regulation & Abolition) Act.' },
      { title: 'PF & ESIC Registration', desc: 'Employer and establishment registration under EPF and ESI Acts.' },
      { title: 'Professional Tax Registration', desc: 'Employer PT registration across all applicable states.' },
      { title: 'MSME / Udyam Registration', desc: 'Udyam portal registration for MSME recognition and government benefits.' },
    ],
    order: 5,
  },
  {
    slug: 'hr-policy-advisory', title: 'HR Policy & Advisory', img: '/assets/service-hr.png',
    desc: 'Custom HR policy design, standing orders and advisory aligned with current labour law mandates.',
    headline: 'Robust HR Policies that Protect Your Organization.',
    subhead: 'HR Policy & Advisory Services',
    intro: 'Drafting HR handbooks, standing orders, POSH policies, and legally compliant employment contracts.',
    body: 'In the era of New Labour Codes, HR policies are not just internal documents — they are legal instruments that can be cited in court proceedings, labour inspections, and employee disputes. Outdated or non-compliant policies create significant exposure.\n\nOur HR advisory team drafts, audits, and updates all your HR documentation — from employment contracts to POSH policies — ensuring they are legally watertight, compliant with the latest codes, and aligned with industry best practices.',
    deliverables: [
      { title: 'HR Policy Manual', desc: 'Comprehensive, legally compliant HR handbook covering all employment policies and procedures.' },
      { title: 'Standing Orders (Certified)', desc: 'Certified Standing Orders under the Industrial Employment (Standing Orders) Act.' },
      { title: 'POSH Policy & ICC Setup', desc: 'Sexual harassment policy drafting and Internal Complaints Committee constitution under POSH Act.' },
      { title: 'Employment Contracts', desc: 'Role-specific employment agreements covering probation, termination, confidentiality, and IP.' },
      { title: 'Offer Letter Templates', desc: 'Legally sound, customizable offer letter formats for all employment levels.' },
      { title: 'Non-Disclosure & Non-Compete Agreements', desc: 'Enforceable NDA and non-compete clauses aligned with Indian contract law.' },
    ],
    order: 6,
  },
  {
    slug: 'litigation-support', title: 'Legal Representation', img: '/assets/service-legal.png',
    desc: 'Skilled representation before labour authorities, tribunals and conciliation boards across states.',
    headline: 'Expert Legal Representation in Labour Disputes.',
    subhead: 'Legal Representation Services',
    intro: 'Labour court representation, conciliation proceedings, and robust litigation support across India.',
    body: "Labour disputes — whether from individual employees, trade unions, or regulatory authorities — can be extremely costly and time-consuming. Expert legal representation at the right stage can significantly alter outcomes and protect your organization's reputation.\n\nOur panel of experienced labour law advocates represents employers before Labour Courts, Industrial Tribunals, High Courts, and in conciliation proceedings before the Conciliation Officer, providing the strongest possible defense and most favorable settlements.",
    deliverables: [
      { title: 'Labour Court Representation', desc: 'Full legal representation before all Labour Courts under the Industrial Disputes Act.' },
      { title: 'Industrial Tribunal Cases', desc: 'Expert advocacy in tribunal proceedings for termination, wage, and recognition disputes.' },
      { title: 'Conciliation Proceedings', desc: 'Strategic representation before the Conciliation Officer to achieve favorable settlements.' },
      { title: 'Inquiry Officer Services', desc: 'Trained inquiry officers for domestic enquiries into employee misconduct.' },
      { title: 'Legal Opinions', desc: 'Written legal opinions on complex labour law questions for management decision-making.' },
      { title: 'Domestic Enquiry Management', desc: 'End-to-end management of disciplinary enquiries — notice, hearing, and enquiry reports.' },
    ],
    order: 7,
  },
  {
    slug: 'training-workshops', title: 'Training & Workshops', img: '/assets/service-training.png',
    desc: 'In-depth labour law training sessions designed to upskill internal HR teams and senior management.',
    headline: 'Empowering Your HR Team with Expert Knowledge.',
    subhead: 'Training & Workshops Services',
    intro: 'In-depth labour law training programs designed to upskill your internal HR teams and management.',
    body: 'Compliance is only as strong as the people implementing it. Non-compliance often stems not from malice but from knowledge gaps in the HR and operations teams. Our training programs equip your teams with the knowledge they need to handle day-to-day compliance confidently.\n\nFrom foundational programs on New Labour Codes to specialized deep-dives on POSH, standing orders, and payroll compliance — our subject-matter experts deliver practical, case-study-driven training that translates directly into better compliance practices.',
    deliverables: [
      { title: 'New Labour Codes Overview', desc: 'Comprehensive training on all 4 Labour Codes and their impact on HR and payroll operations.' },
      { title: 'POSH Act Training & ICC', desc: 'Mandatory POSH awareness sessions for employees and specialized training for ICC members.' },
      { title: 'Payroll Compliance Workshop', desc: 'Hands-on workshop covering wage definition, statutory deductions, and new-age payroll compliance.' },
      { title: 'HR Documentation Workshop', desc: 'Practical sessions on drafting, maintaining, and auditing statutory registers and HR documents.' },
      { title: 'Factory Act Training', desc: 'Training for factory managers and HR on obligations under the Factories Act and safety rules.' },
      { title: 'Custom In-house Programs', desc: 'Bespoke training programs designed around your industry, workforce size, and compliance gaps.' },
    ],
    order: 8,
  },
];
